### ISSUE TITLE
error while updating property 'transform' of a view managed by rctview

### ISSUE THREAD

**Issue by mdshadman** [VGoose/react-native-realistic-deck-swiper#4]
![Screenshot_2019-04-24-12-14-24-33](https://user-images.githubusercontent.com/39180102/56638042-bdf54a80-668a-11e9-8b86-01a9eb87c9d9.png)

I am facing this problem while running your example in expo. Please suggest me the solution.

**Comment by VGoose** [comment]
Hey @mdshadman sorry I'm only getting to this now - did you make any changes to the example code?

**Comment by mdshadman** [comment]
no i haven't

**Comment by Osama92** [comment]
I'm Also getting the same Error as above, Advice a fix, please.

**Comment by VGoose** [comment]
Hi guys, I just cloned the repo and tried and it worked for me.  Might be an issue with expo-cli versions.  What version is everyone running?

**Comment by VGoose** [comment]
OK - it's not expo; it's related to [#9841](https://github.com/facebook/react-native/issues/9841).  Android seems to not like the transform property values from our Animated values.

**Comment by VGoose** [comment]
Found the bug - will release fix soon :).  Thanks for your patience.

**Comment by VGoose** [comment]
fixed with v0.1.3
